### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by grimnight** [ctrlcctrlv/FRBCistercian#2]
I have been trying to use this font, but have been unable to get it to work.
Could you provide some intructions?

I use Linux.

**Comment by ctrlcctrlv** [comment]
Install, enter the codepoints in https://github.com/ctrlcctrlv/FRBCistercian/blob/main/codepoints.tsv into a document.

**Comment by grimnight** [comment]
I'm currently trying to get it to work on the commandline:
```terminal
❯ echo \U100026\U10001d\U100002\U100014\U10000b
􀀝􀀂􀀔􀀋
```
Unfortunately it doesn't seem to be working, am I doing something wrong?

**Comment by ctrlcctrlv** [comment]
Because these characters are in the Private Use Area (PUA), fontconfig may not pick them up by default. You may need to tell fontconfig to consider FRB Cistercian as one of your fallback fonts.

As an example, on my system this file is provided by the Noto Sans package:

# `/usr/share/fontconfig/conf.avail/66-noto-sans.conf`

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Sans</family>
    </prefer>
  </alias>
</fontconfig>
```

This assures that Noto Sans is one of the fonts considered when `sans-serif` is requested.

So you may need:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>FRB Cistercian</family>
    </prefer>
  </alias>
</fontconfig>
```

However, some terminal emulators may continue to reject it if it doesn't pass the monospace tests. That depends on your terminal emulator.

**Comment by ctrlcctrlv** [comment]
I did not have to do this with kitty terminal emulator though, simply installing the font worked for me.

![Screenshot_20240528_095853](https://github.com/ctrlcctrlv/FRBCistercian/assets/838783/261aa510-8123-4165-9931-fdfc3d97eade)
